"""Add scoring and resume columns

Revision ID: 2733ee392aa1
Revises: 3f41a8eedcee
Create Date: 2026-03-19 05:45:44.100114

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2733ee392aa1'
down_revision: Union[str, Sequence[str], None] = '3f41a8eedcee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('fit_score', sa.Integer(), nullable=True))
    op.add_column('jobs', sa.Column('recommended_resume', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'recommended_resume')
    op.drop_column('jobs', 'fit_score')
    # ### end Alembic commands ###
