"""Add description_text column to jobs

Revision ID: 3f41a8eedcee
Revises: 0c9688c28f22
Create Date: 2026-03-19 05:38:47.161514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3f41a8eedcee'
down_revision: Union[str, Sequence[str], None] = '0c9688c28f22'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('description_text', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'description_text')
    # ### end Alembic commands ###
