"""add_cover_letter_to_jobs

Revision ID: a18ea51b76fd
Revises: 8d6b7f2e1c4a
Create Date: 2026-04-02 04:33:33.354640

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'a18ea51b76fd'
down_revision: Union[str, Sequence[str], None] = '8d6b7f2e1c4a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('jobs', sa.Column('cover_letter', sa.Text(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('jobs', 'cover_letter')
    # ### end Alembic commands ###
