"""add_interview_prep_sheet

Revision ID: b16bb02fc7ed
Revises: a18ea51b76fd
Create Date: 2026-05-02 11:19:16.704168

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b16bb02fc7ed'
down_revision: Union[str, Sequence[str], None] = 'a18ea51b76fd'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('interview_prep_sheets',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_application_id', sa.Integer(), nullable=False),
    sa.Column('status', sa.String(), nullable=False),
    sa.Column('company_snapshot', sa.Text(), nullable=True),
    sa.Column('role_requirements_summary', sa.Text(), nullable=True),
    sa.Column('likely_technical_questions', sa.Text(), nullable=True),
    sa.Column('likely_behavioral_questions', sa.Text(), nullable=True),
    sa.Column('talking_points', sa.Text(), nullable=True),
    sa.Column('gaps_or_risks', sa.Text(), nullable=True),
    sa.Column('prep_plan_30_min', sa.Text(), nullable=True),
    sa.Column('error_message', sa.Text(), nullable=True),
    sa.Column('generated_at', sa.DateTime(), nullable=True),
    sa.Column('created_at', sa.DateTime(), nullable=True),
    sa.ForeignKeyConstraint(['job_application_id'], ['jobs.id'], ),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('job_application_id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('interview_prep_sheets')
    # ### end Alembic commands ###
